### ISSUE TITLE
Установка проходит с ошибкой

### ISSUE THREAD

**Issue by lancedikson** [htmlhero/grunt-init-block#8]
Выполнил `npm install grunt-init-block --save-dev`. Вот что вижу: 

```
npm install grunt-init-block --save-dev
…
…
npm http 200 https://registry.npmjs.org/CSSselect
npm http GET https://registry.npmjs.org/CSSselect/-/CSSselect-0.4.0.tgz
npm http GET https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/domelementtype
npm http 200 https://registry.npmjs.org/domutils
npm http 200 https://registry.npmjs.org/domhandler
npm http 200 https://registry.npmjs.org/CSSselect/-/CSSselect-0.4.0.tgz
npm http 200 https://registry.npmjs.org/readable-stream
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/domutils/-/domutils-1.3.0.tgz
npm http GET https://registry.npmjs.org/CSSwhat
npm http 200 https://registry.npmjs.org/graceful-fs

> execSync@1.0.1-pre install d:\Dropbox\Apache\odintsova.loc\node_modules\grunt-init-block\node_modules\copy-paste\node_modules\execSync
> node-gyp rebuild


d:\Dropbox\Apache\odintsova.loc\node_modules\grunt-init-block\node_modules\copy-paste\node_modules\execSync>node "c:\Program Files\nodejs\node_modules\npm\bin\n
ode-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 200 https://registry.npmjs.org/domutils/-/domutils-1.3.0.tgz
npm http 200 https://registry.npmjs.org/CSSwhat
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:118:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:81:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\Dropbox\Apache\odintsova.loc\node_modules\grunt-init-block\node_modules\copy-paste\node_modules\execSync
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

Это он Питона хочет? А без него работать не будет?

**Comment by htmlhero** [comment]
Напрямую Питон не используется. Похоже, он нужен модулю [copy-paste](https://npmjs.org/package/copy-paste). По ссылке указано, что ему нужно для работы в Windows.

**Comment by lancedikson** [comment]
@htmlhero дошли руки снова попробовать модуль, вернулся к той же ошибке. Установил Python 3.3. copy-paste начал ругаться, что нужна версия < 3.0. Поставил. Теперь вижу такую ошибку:

`gyp http GET http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.21/x64/node.lib
gyp http GET http://nodejs.org/dist/v0.10.21/x64/node.lib
gyp http GET http://nodejs.org/dist/v0.10.21/node.lib
gyp http GET http://nodejs.org/dist/v0.10.21/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.21/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.21/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.21/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.21/node.lib
Построение проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
d:\Dropbox\Apache\fstroy.loc\node_modules\grunt-init-block\node_modules\copy-paste\node_modules\execSync\build\shell.vcxproj(18,3): error MSB4019: импортирован
ный проект "d:\Microsoft.Cpp.Default.props" не обнаружен. Проверьте путь в объявлении <Import> и наличие файла на диске.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\Dropbox\Apache\fstroy.loc\node_modules\grunt-init-block\node_modules\copy-paste\node_modules\execSync
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'd:\Dropbox\Apache\fstroy.loc\node_modules\grunt-init-block\node_modules\cheerio\node_modules\htmlparser2\te
sts\Events'
npm ERR! error rolling back  grunt-init-block@0.2.0 { [Error: ENOTEMPTY, rmdir 'd:\Dropbox\Apache\fstroy.loc\node_modules\grunt-init-block\node_modules\cheerio\
node_modules\htmlparser2\tests\Events']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'd:\\Dropbox\\Apache\\fstroy.loc\\node_modules\\grunt-init-block\\node_modules\\cheerio\\node_modules\\htmlparser2\\tests\\E
vents' }
npm ERR! weird error 1
npm ERR! not ok code 0`
